version: "3"
services:
  flask-compose:
    build: ./flask
    ports: ['8085:8085']
    volumes: ['./flask:/app']

  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports: ['5432:5432']
    volumes: ['./postgres:/var/lib/postgresql/data']
    networks: ['postgres-compose-network']
          
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ott.html@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports: ['80:80']
    depends_on: ['postgres-compose']
    networks: ['postgres-compose-network']
    
networks: 
  postgres-compose-network:
    driver: bridge
